//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("VinnitsaModelNamespace", "FK_tblComments_tblAssortments", "tblAssortments", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(VinnitsaJunkFood.DataAccessLayer.tblAssortments), "tblComments", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VinnitsaJunkFood.DataAccessLayer.tblComments), true)]
[assembly: EdmRelationshipAttribute("VinnitsaModelNamespace", "FK_tblIngridientsAssortment_tblAssortment", "tblAssortments", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VinnitsaJunkFood.DataAccessLayer.tblAssortments), "tblIngridientsAssortments", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VinnitsaJunkFood.DataAccessLayer.tblIngridientsAssortments), true)]
[assembly: EdmRelationshipAttribute("VinnitsaModelNamespace", "FK_tblPriceList_tblAssortment", "tblAssortments", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VinnitsaJunkFood.DataAccessLayer.tblAssortments), "tblPriceLists", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VinnitsaJunkFood.DataAccessLayer.tblPriceLists), true)]
[assembly: EdmRelationshipAttribute("VinnitsaModelNamespace", "FK_tblComments_tblOutlets", "tblOutlets", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VinnitsaJunkFood.DataAccessLayer.tblOutlets), "tblComments", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VinnitsaJunkFood.DataAccessLayer.tblComments), true)]
[assembly: EdmRelationshipAttribute("VinnitsaModelNamespace", "FK_tblIngridientsAssortment_tblIngridients", "tblIngridients", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VinnitsaJunkFood.DataAccessLayer.tblIngridients), "tblIngridientsAssortments", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VinnitsaJunkFood.DataAccessLayer.tblIngridientsAssortments), true)]
[assembly: EdmRelationshipAttribute("VinnitsaModelNamespace", "FK_tblPriceList_tblOutlets", "tblOutlets", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VinnitsaJunkFood.DataAccessLayer.tblOutlets), "tblPriceLists", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VinnitsaJunkFood.DataAccessLayer.tblPriceLists), true)]

#endregion

namespace VinnitsaJunkFood.DataAccessLayer
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class VinnitsaEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new VinnitsaEntities object using the connection string found in the 'VinnitsaEntities' section of the application configuration file.
        /// </summary>
        public VinnitsaEntities() : base("name=VinnitsaEntities", "VinnitsaEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new VinnitsaEntities object.
        /// </summary>
        public VinnitsaEntities(string connectionString) : base(connectionString, "VinnitsaEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new VinnitsaEntities object.
        /// </summary>
        public VinnitsaEntities(EntityConnection connection) : base(connection, "VinnitsaEntities")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblAssortments> tblAssortments
        {
            get
            {
                if ((_tblAssortments == null))
                {
                    _tblAssortments = base.CreateObjectSet<tblAssortments>("tblAssortments");
                }
                return _tblAssortments;
            }
        }
        private ObjectSet<tblAssortments> _tblAssortments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblComments> tblComments
        {
            get
            {
                if ((_tblComments == null))
                {
                    _tblComments = base.CreateObjectSet<tblComments>("tblComments");
                }
                return _tblComments;
            }
        }
        private ObjectSet<tblComments> _tblComments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblIngridients> tblIngridients
        {
            get
            {
                if ((_tblIngridients == null))
                {
                    _tblIngridients = base.CreateObjectSet<tblIngridients>("tblIngridients");
                }
                return _tblIngridients;
            }
        }
        private ObjectSet<tblIngridients> _tblIngridients;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblIngridientsAssortments> tblIngridientsAssortments
        {
            get
            {
                if ((_tblIngridientsAssortments == null))
                {
                    _tblIngridientsAssortments = base.CreateObjectSet<tblIngridientsAssortments>("tblIngridientsAssortments");
                }
                return _tblIngridientsAssortments;
            }
        }
        private ObjectSet<tblIngridientsAssortments> _tblIngridientsAssortments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblOutlets> tblOutlets
        {
            get
            {
                if ((_tblOutlets == null))
                {
                    _tblOutlets = base.CreateObjectSet<tblOutlets>("tblOutlets");
                }
                return _tblOutlets;
            }
        }
        private ObjectSet<tblOutlets> _tblOutlets;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblPriceLists> tblPriceLists
        {
            get
            {
                if ((_tblPriceLists == null))
                {
                    _tblPriceLists = base.CreateObjectSet<tblPriceLists>("tblPriceLists");
                }
                return _tblPriceLists;
            }
        }
        private ObjectSet<tblPriceLists> _tblPriceLists;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblAssortments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblAssortments(tblAssortments tblAssortments)
        {
            base.AddObject("tblAssortments", tblAssortments);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblComments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblComments(tblComments tblComments)
        {
            base.AddObject("tblComments", tblComments);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblIngridients EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblIngridients(tblIngridients tblIngridients)
        {
            base.AddObject("tblIngridients", tblIngridients);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblIngridientsAssortments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblIngridientsAssortments(tblIngridientsAssortments tblIngridientsAssortments)
        {
            base.AddObject("tblIngridientsAssortments", tblIngridientsAssortments);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblOutlets EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblOutlets(tblOutlets tblOutlets)
        {
            base.AddObject("tblOutlets", tblOutlets);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblPriceLists EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblPriceLists(tblPriceLists tblPriceLists)
        {
            base.AddObject("tblPriceLists", tblPriceLists);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VinnitsaModelNamespace", Name="tblAssortments")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblAssortments : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblAssortments object.
        /// </summary>
        /// <param name="iAssortmentId">Initial value of the iAssortmentId property.</param>
        /// <param name="nvcAssortmentName">Initial value of the nvcAssortmentName property.</param>
        public static tblAssortments CreatetblAssortments(global::System.Int32 iAssortmentId, global::System.String nvcAssortmentName)
        {
            tblAssortments tblAssortments = new tblAssortments();
            tblAssortments.iAssortmentId = iAssortmentId;
            tblAssortments.nvcAssortmentName = nvcAssortmentName;
            return tblAssortments;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 iAssortmentId
        {
            get
            {
                return _iAssortmentId;
            }
            set
            {
                if (_iAssortmentId != value)
                {
                    OniAssortmentIdChanging(value);
                    ReportPropertyChanging("iAssortmentId");
                    _iAssortmentId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("iAssortmentId");
                    OniAssortmentIdChanged();
                }
            }
        }
        private global::System.Int32 _iAssortmentId;
        partial void OniAssortmentIdChanging(global::System.Int32 value);
        partial void OniAssortmentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nvcAssortmentName
        {
            get
            {
                return _nvcAssortmentName;
            }
            set
            {
                OnnvcAssortmentNameChanging(value);
                ReportPropertyChanging("nvcAssortmentName");
                _nvcAssortmentName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nvcAssortmentName");
                OnnvcAssortmentNameChanged();
            }
        }
        private global::System.String _nvcAssortmentName;
        partial void OnnvcAssortmentNameChanging(global::System.String value);
        partial void OnnvcAssortmentNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nvcDescription
        {
            get
            {
                return _nvcDescription;
            }
            set
            {
                OnnvcDescriptionChanging(value);
                ReportPropertyChanging("nvcDescription");
                _nvcDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nvcDescription");
                OnnvcDescriptionChanged();
            }
        }
        private global::System.String _nvcDescription;
        partial void OnnvcDescriptionChanging(global::System.String value);
        partial void OnnvcDescriptionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VinnitsaModelNamespace", "FK_tblComments_tblAssortments", "tblComments")]
        public EntityCollection<tblComments> tblComments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblComments>("VinnitsaModelNamespace.FK_tblComments_tblAssortments", "tblComments");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblComments>("VinnitsaModelNamespace.FK_tblComments_tblAssortments", "tblComments", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VinnitsaModelNamespace", "FK_tblIngridientsAssortment_tblAssortment", "tblIngridientsAssortments")]
        public EntityCollection<tblIngridientsAssortments> tblIngridientsAssortments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblIngridientsAssortments>("VinnitsaModelNamespace.FK_tblIngridientsAssortment_tblAssortment", "tblIngridientsAssortments");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblIngridientsAssortments>("VinnitsaModelNamespace.FK_tblIngridientsAssortment_tblAssortment", "tblIngridientsAssortments", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VinnitsaModelNamespace", "FK_tblPriceList_tblAssortment", "tblPriceLists")]
        public EntityCollection<tblPriceLists> tblPriceLists
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblPriceLists>("VinnitsaModelNamespace.FK_tblPriceList_tblAssortment", "tblPriceLists");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblPriceLists>("VinnitsaModelNamespace.FK_tblPriceList_tblAssortment", "tblPriceLists", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VinnitsaModelNamespace", Name="tblComments")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblComments : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblComments object.
        /// </summary>
        /// <param name="iCommentId">Initial value of the iCommentId property.</param>
        /// <param name="iOutletId">Initial value of the iOutletId property.</param>
        /// <param name="dtCommentDateTime">Initial value of the dtCommentDateTime property.</param>
        /// <param name="nvcCommentText">Initial value of the nvcCommentText property.</param>
        public static tblComments CreatetblComments(global::System.Int32 iCommentId, global::System.Int32 iOutletId, global::System.DateTime dtCommentDateTime, global::System.String nvcCommentText)
        {
            tblComments tblComments = new tblComments();
            tblComments.iCommentId = iCommentId;
            tblComments.iOutletId = iOutletId;
            tblComments.dtCommentDateTime = dtCommentDateTime;
            tblComments.nvcCommentText = nvcCommentText;
            return tblComments;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 iCommentId
        {
            get
            {
                return _iCommentId;
            }
            set
            {
                if (_iCommentId != value)
                {
                    OniCommentIdChanging(value);
                    ReportPropertyChanging("iCommentId");
                    _iCommentId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("iCommentId");
                    OniCommentIdChanged();
                }
            }
        }
        private global::System.Int32 _iCommentId;
        partial void OniCommentIdChanging(global::System.Int32 value);
        partial void OniCommentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 iOutletId
        {
            get
            {
                return _iOutletId;
            }
            set
            {
                OniOutletIdChanging(value);
                ReportPropertyChanging("iOutletId");
                _iOutletId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("iOutletId");
                OniOutletIdChanged();
            }
        }
        private global::System.Int32 _iOutletId;
        partial void OniOutletIdChanging(global::System.Int32 value);
        partial void OniOutletIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime dtCommentDateTime
        {
            get
            {
                return _dtCommentDateTime;
            }
            set
            {
                OndtCommentDateTimeChanging(value);
                ReportPropertyChanging("dtCommentDateTime");
                _dtCommentDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dtCommentDateTime");
                OndtCommentDateTimeChanged();
            }
        }
        private global::System.DateTime _dtCommentDateTime;
        partial void OndtCommentDateTimeChanging(global::System.DateTime value);
        partial void OndtCommentDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nvcCommentText
        {
            get
            {
                return _nvcCommentText;
            }
            set
            {
                OnnvcCommentTextChanging(value);
                ReportPropertyChanging("nvcCommentText");
                _nvcCommentText = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nvcCommentText");
                OnnvcCommentTextChanged();
            }
        }
        private global::System.String _nvcCommentText;
        partial void OnnvcCommentTextChanging(global::System.String value);
        partial void OnnvcCommentTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nvcUserName
        {
            get
            {
                return _nvcUserName;
            }
            set
            {
                OnnvcUserNameChanging(value);
                ReportPropertyChanging("nvcUserName");
                _nvcUserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nvcUserName");
                OnnvcUserNameChanged();
            }
        }
        private global::System.String _nvcUserName;
        partial void OnnvcUserNameChanging(global::System.String value);
        partial void OnnvcUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> iAssortmentId
        {
            get
            {
                return _iAssortmentId;
            }
            set
            {
                OniAssortmentIdChanging(value);
                ReportPropertyChanging("iAssortmentId");
                _iAssortmentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("iAssortmentId");
                OniAssortmentIdChanged();
            }
        }
        private Nullable<global::System.Int32> _iAssortmentId;
        partial void OniAssortmentIdChanging(Nullable<global::System.Int32> value);
        partial void OniAssortmentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> iCommentRating
        {
            get
            {
                return _iCommentRating;
            }
            set
            {
                OniCommentRatingChanging(value);
                ReportPropertyChanging("iCommentRating");
                _iCommentRating = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("iCommentRating");
                OniCommentRatingChanged();
            }
        }
        private Nullable<global::System.Int32> _iCommentRating;
        partial void OniCommentRatingChanging(Nullable<global::System.Int32> value);
        partial void OniCommentRatingChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VinnitsaModelNamespace", "FK_tblComments_tblAssortments", "tblAssortments")]
        public tblAssortments tblAssortments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblAssortments>("VinnitsaModelNamespace.FK_tblComments_tblAssortments", "tblAssortments").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblAssortments>("VinnitsaModelNamespace.FK_tblComments_tblAssortments", "tblAssortments").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblAssortments> tblAssortmentsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblAssortments>("VinnitsaModelNamespace.FK_tblComments_tblAssortments", "tblAssortments");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblAssortments>("VinnitsaModelNamespace.FK_tblComments_tblAssortments", "tblAssortments", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VinnitsaModelNamespace", "FK_tblComments_tblOutlets", "tblOutlets")]
        public tblOutlets tblOutlets
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblOutlets>("VinnitsaModelNamespace.FK_tblComments_tblOutlets", "tblOutlets").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblOutlets>("VinnitsaModelNamespace.FK_tblComments_tblOutlets", "tblOutlets").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblOutlets> tblOutletsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblOutlets>("VinnitsaModelNamespace.FK_tblComments_tblOutlets", "tblOutlets");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblOutlets>("VinnitsaModelNamespace.FK_tblComments_tblOutlets", "tblOutlets", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VinnitsaModelNamespace", Name="tblIngridients")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblIngridients : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblIngridients object.
        /// </summary>
        /// <param name="iIngridientId">Initial value of the iIngridientId property.</param>
        /// <param name="nvcDescription">Initial value of the nvcDescription property.</param>
        public static tblIngridients CreatetblIngridients(global::System.Int32 iIngridientId, global::System.String nvcDescription)
        {
            tblIngridients tblIngridients = new tblIngridients();
            tblIngridients.iIngridientId = iIngridientId;
            tblIngridients.nvcDescription = nvcDescription;
            return tblIngridients;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 iIngridientId
        {
            get
            {
                return _iIngridientId;
            }
            set
            {
                if (_iIngridientId != value)
                {
                    OniIngridientIdChanging(value);
                    ReportPropertyChanging("iIngridientId");
                    _iIngridientId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("iIngridientId");
                    OniIngridientIdChanged();
                }
            }
        }
        private global::System.Int32 _iIngridientId;
        partial void OniIngridientIdChanging(global::System.Int32 value);
        partial void OniIngridientIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nvcDescription
        {
            get
            {
                return _nvcDescription;
            }
            set
            {
                OnnvcDescriptionChanging(value);
                ReportPropertyChanging("nvcDescription");
                _nvcDescription = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nvcDescription");
                OnnvcDescriptionChanged();
            }
        }
        private global::System.String _nvcDescription;
        partial void OnnvcDescriptionChanging(global::System.String value);
        partial void OnnvcDescriptionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VinnitsaModelNamespace", "FK_tblIngridientsAssortment_tblIngridients", "tblIngridientsAssortments")]
        public EntityCollection<tblIngridientsAssortments> tblIngridientsAssortments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblIngridientsAssortments>("VinnitsaModelNamespace.FK_tblIngridientsAssortment_tblIngridients", "tblIngridientsAssortments");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblIngridientsAssortments>("VinnitsaModelNamespace.FK_tblIngridientsAssortment_tblIngridients", "tblIngridientsAssortments", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VinnitsaModelNamespace", Name="tblIngridientsAssortments")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblIngridientsAssortments : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblIngridientsAssortments object.
        /// </summary>
        /// <param name="iAssortmentId">Initial value of the iAssortmentId property.</param>
        /// <param name="iIngridientId">Initial value of the iIngridientId property.</param>
        /// <param name="iCount">Initial value of the iCount property.</param>
        public static tblIngridientsAssortments CreatetblIngridientsAssortments(global::System.Int32 iAssortmentId, global::System.Int32 iIngridientId, global::System.Int16 iCount)
        {
            tblIngridientsAssortments tblIngridientsAssortments = new tblIngridientsAssortments();
            tblIngridientsAssortments.iAssortmentId = iAssortmentId;
            tblIngridientsAssortments.iIngridientId = iIngridientId;
            tblIngridientsAssortments.iCount = iCount;
            return tblIngridientsAssortments;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 iAssortmentId
        {
            get
            {
                return _iAssortmentId;
            }
            set
            {
                if (_iAssortmentId != value)
                {
                    OniAssortmentIdChanging(value);
                    ReportPropertyChanging("iAssortmentId");
                    _iAssortmentId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("iAssortmentId");
                    OniAssortmentIdChanged();
                }
            }
        }
        private global::System.Int32 _iAssortmentId;
        partial void OniAssortmentIdChanging(global::System.Int32 value);
        partial void OniAssortmentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 iIngridientId
        {
            get
            {
                return _iIngridientId;
            }
            set
            {
                if (_iIngridientId != value)
                {
                    OniIngridientIdChanging(value);
                    ReportPropertyChanging("iIngridientId");
                    _iIngridientId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("iIngridientId");
                    OniIngridientIdChanged();
                }
            }
        }
        private global::System.Int32 _iIngridientId;
        partial void OniIngridientIdChanging(global::System.Int32 value);
        partial void OniIngridientIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 iCount
        {
            get
            {
                return _iCount;
            }
            set
            {
                if (_iCount != value)
                {
                    OniCountChanging(value);
                    ReportPropertyChanging("iCount");
                    _iCount = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("iCount");
                    OniCountChanged();
                }
            }
        }
        private global::System.Int16 _iCount;
        partial void OniCountChanging(global::System.Int16 value);
        partial void OniCountChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VinnitsaModelNamespace", "FK_tblIngridientsAssortment_tblAssortment", "tblAssortments")]
        public tblAssortments tblAssortments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblAssortments>("VinnitsaModelNamespace.FK_tblIngridientsAssortment_tblAssortment", "tblAssortments").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblAssortments>("VinnitsaModelNamespace.FK_tblIngridientsAssortment_tblAssortment", "tblAssortments").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblAssortments> tblAssortmentsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblAssortments>("VinnitsaModelNamespace.FK_tblIngridientsAssortment_tblAssortment", "tblAssortments");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblAssortments>("VinnitsaModelNamespace.FK_tblIngridientsAssortment_tblAssortment", "tblAssortments", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VinnitsaModelNamespace", "FK_tblIngridientsAssortment_tblIngridients", "tblIngridients")]
        public tblIngridients tblIngridients
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblIngridients>("VinnitsaModelNamespace.FK_tblIngridientsAssortment_tblIngridients", "tblIngridients").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblIngridients>("VinnitsaModelNamespace.FK_tblIngridientsAssortment_tblIngridients", "tblIngridients").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblIngridients> tblIngridientsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblIngridients>("VinnitsaModelNamespace.FK_tblIngridientsAssortment_tblIngridients", "tblIngridients");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblIngridients>("VinnitsaModelNamespace.FK_tblIngridientsAssortment_tblIngridients", "tblIngridients", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VinnitsaModelNamespace", Name="tblOutlets")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblOutlets : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblOutlets object.
        /// </summary>
        /// <param name="iOutletId">Initial value of the iOutletId property.</param>
        /// <param name="nvcOutletName">Initial value of the nvcOutletName property.</param>
        /// <param name="fLatitude">Initial value of the fLatitude property.</param>
        /// <param name="fLongitude">Initial value of the fLongitude property.</param>
        public static tblOutlets CreatetblOutlets(global::System.Int32 iOutletId, global::System.String nvcOutletName, global::System.Double fLatitude, global::System.Double fLongitude)
        {
            tblOutlets tblOutlets = new tblOutlets();
            tblOutlets.iOutletId = iOutletId;
            tblOutlets.nvcOutletName = nvcOutletName;
            tblOutlets.fLatitude = fLatitude;
            tblOutlets.fLongitude = fLongitude;
            return tblOutlets;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 iOutletId
        {
            get
            {
                return _iOutletId;
            }
            set
            {
                if (_iOutletId != value)
                {
                    OniOutletIdChanging(value);
                    ReportPropertyChanging("iOutletId");
                    _iOutletId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("iOutletId");
                    OniOutletIdChanged();
                }
            }
        }
        private global::System.Int32 _iOutletId;
        partial void OniOutletIdChanging(global::System.Int32 value);
        partial void OniOutletIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nvcOutletName
        {
            get
            {
                return _nvcOutletName;
            }
            set
            {
                OnnvcOutletNameChanging(value);
                ReportPropertyChanging("nvcOutletName");
                _nvcOutletName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nvcOutletName");
                OnnvcOutletNameChanged();
            }
        }
        private global::System.String _nvcOutletName;
        partial void OnnvcOutletNameChanging(global::System.String value);
        partial void OnnvcOutletNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double fLatitude
        {
            get
            {
                return _fLatitude;
            }
            set
            {
                OnfLatitudeChanging(value);
                ReportPropertyChanging("fLatitude");
                _fLatitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fLatitude");
                OnfLatitudeChanged();
            }
        }
        private global::System.Double _fLatitude;
        partial void OnfLatitudeChanging(global::System.Double value);
        partial void OnfLatitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double fLongitude
        {
            get
            {
                return _fLongitude;
            }
            set
            {
                OnfLongitudeChanging(value);
                ReportPropertyChanging("fLongitude");
                _fLongitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fLongitude");
                OnfLongitudeChanged();
            }
        }
        private global::System.Double _fLongitude;
        partial void OnfLongitudeChanging(global::System.Double value);
        partial void OnfLongitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nvcDescription
        {
            get
            {
                return _nvcDescription;
            }
            set
            {
                OnnvcDescriptionChanging(value);
                ReportPropertyChanging("nvcDescription");
                _nvcDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nvcDescription");
                OnnvcDescriptionChanged();
            }
        }
        private global::System.String _nvcDescription;
        partial void OnnvcDescriptionChanging(global::System.String value);
        partial void OnnvcDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> rRating
        {
            get
            {
                return _rRating;
            }
            set
            {
                OnrRatingChanging(value);
                ReportPropertyChanging("rRating");
                _rRating = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rRating");
                OnrRatingChanged();
            }
        }
        private Nullable<global::System.Single> _rRating;
        partial void OnrRatingChanging(Nullable<global::System.Single> value);
        partial void OnrRatingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nvcImagePath
        {
            get
            {
                return _nvcImagePath;
            }
            set
            {
                OnnvcImagePathChanging(value);
                ReportPropertyChanging("nvcImagePath");
                _nvcImagePath = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nvcImagePath");
                OnnvcImagePathChanged();
            }
        }
        private global::System.String _nvcImagePath;
        partial void OnnvcImagePathChanging(global::System.String value);
        partial void OnnvcImagePathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> iVotes
        {
            get
            {
                return _iVotes;
            }
            set
            {
                OniVotesChanging(value);
                ReportPropertyChanging("iVotes");
                _iVotes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("iVotes");
                OniVotesChanged();
            }
        }
        private Nullable<global::System.Int32> _iVotes;
        partial void OniVotesChanging(Nullable<global::System.Int32> value);
        partial void OniVotesChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VinnitsaModelNamespace", "FK_tblComments_tblOutlets", "tblComments")]
        public EntityCollection<tblComments> tblComments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblComments>("VinnitsaModelNamespace.FK_tblComments_tblOutlets", "tblComments");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblComments>("VinnitsaModelNamespace.FK_tblComments_tblOutlets", "tblComments", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VinnitsaModelNamespace", "FK_tblPriceList_tblOutlets", "tblPriceLists")]
        public EntityCollection<tblPriceLists> tblPriceLists
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblPriceLists>("VinnitsaModelNamespace.FK_tblPriceList_tblOutlets", "tblPriceLists");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblPriceLists>("VinnitsaModelNamespace.FK_tblPriceList_tblOutlets", "tblPriceLists", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VinnitsaModelNamespace", Name="tblPriceLists")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblPriceLists : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblPriceLists object.
        /// </summary>
        /// <param name="iPriceId">Initial value of the iPriceId property.</param>
        /// <param name="iOutletId">Initial value of the iOutletId property.</param>
        /// <param name="iAssortmentId">Initial value of the iAssortmentId property.</param>
        /// <param name="fPrice">Initial value of the fPrice property.</param>
        public static tblPriceLists CreatetblPriceLists(global::System.Int32 iPriceId, global::System.Int32 iOutletId, global::System.Int32 iAssortmentId, global::System.Decimal fPrice)
        {
            tblPriceLists tblPriceLists = new tblPriceLists();
            tblPriceLists.iPriceId = iPriceId;
            tblPriceLists.iOutletId = iOutletId;
            tblPriceLists.iAssortmentId = iAssortmentId;
            tblPriceLists.fPrice = fPrice;
            return tblPriceLists;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 iPriceId
        {
            get
            {
                return _iPriceId;
            }
            set
            {
                if (_iPriceId != value)
                {
                    OniPriceIdChanging(value);
                    ReportPropertyChanging("iPriceId");
                    _iPriceId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("iPriceId");
                    OniPriceIdChanged();
                }
            }
        }
        private global::System.Int32 _iPriceId;
        partial void OniPriceIdChanging(global::System.Int32 value);
        partial void OniPriceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 iOutletId
        {
            get
            {
                return _iOutletId;
            }
            set
            {
                OniOutletIdChanging(value);
                ReportPropertyChanging("iOutletId");
                _iOutletId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("iOutletId");
                OniOutletIdChanged();
            }
        }
        private global::System.Int32 _iOutletId;
        partial void OniOutletIdChanging(global::System.Int32 value);
        partial void OniOutletIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 iAssortmentId
        {
            get
            {
                return _iAssortmentId;
            }
            set
            {
                OniAssortmentIdChanging(value);
                ReportPropertyChanging("iAssortmentId");
                _iAssortmentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("iAssortmentId");
                OniAssortmentIdChanged();
            }
        }
        private global::System.Int32 _iAssortmentId;
        partial void OniAssortmentIdChanging(global::System.Int32 value);
        partial void OniAssortmentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal fPrice
        {
            get
            {
                return _fPrice;
            }
            set
            {
                OnfPriceChanging(value);
                ReportPropertyChanging("fPrice");
                _fPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fPrice");
                OnfPriceChanged();
            }
        }
        private global::System.Decimal _fPrice;
        partial void OnfPriceChanging(global::System.Decimal value);
        partial void OnfPriceChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VinnitsaModelNamespace", "FK_tblPriceList_tblAssortment", "tblAssortments")]
        public tblAssortments tblAssortments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblAssortments>("VinnitsaModelNamespace.FK_tblPriceList_tblAssortment", "tblAssortments").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblAssortments>("VinnitsaModelNamespace.FK_tblPriceList_tblAssortment", "tblAssortments").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblAssortments> tblAssortmentsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblAssortments>("VinnitsaModelNamespace.FK_tblPriceList_tblAssortment", "tblAssortments");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblAssortments>("VinnitsaModelNamespace.FK_tblPriceList_tblAssortment", "tblAssortments", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VinnitsaModelNamespace", "FK_tblPriceList_tblOutlets", "tblOutlets")]
        public tblOutlets tblOutlets
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblOutlets>("VinnitsaModelNamespace.FK_tblPriceList_tblOutlets", "tblOutlets").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblOutlets>("VinnitsaModelNamespace.FK_tblPriceList_tblOutlets", "tblOutlets").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblOutlets> tblOutletsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblOutlets>("VinnitsaModelNamespace.FK_tblPriceList_tblOutlets", "tblOutlets");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblOutlets>("VinnitsaModelNamespace.FK_tblPriceList_tblOutlets", "tblOutlets", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
